"""Initial migration

Revision ID: f44064176140
Revises: 
Create Date: 2026-05-04 21:21:24.886594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44064176140'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_x', sa.Float(), nullable=True),
    sa.Column('location_y', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibitions_id'), 'exhibitions', ['id'], unique=False)
    op.create_index(op.f('ix_exhibitions_name'), 'exhibitions', ['name'], unique=False)
    op.create_table('wait_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exhibition_id', sa.Integer(), nullable=True),
    sa.Column('current_wait_minutes', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wait_times_id'), 'wait_times', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wait_times_id'), table_name='wait_times')
    op.drop_table('wait_times')
    op.drop_index(op.f('ix_exhibitions_name'), table_name='exhibitions')
    op.drop_index(op.f('ix_exhibitions_id'), table_name='exhibitions')
    op.drop_table('exhibitions')
    # ### end Alembic commands ###
